"""
StyleEcho 언어 상수
====================
구어체 연음/축약 패턴 사전 및 기본 고빈도 단어 목록.
engine.py 의 문장 파싱 로직에서 사용됩니다.
"""

REDUCTION_PATTERNS: dict[str, str] = {
    "going to": "gonna",
    "want to": "wanna",
    "got to": "gotta",
    "got you": "gotcha",
    "kind of": "kinda",
    "sort of": "sorta",
    "out of": "outta",
    "a lot of": "alotta",
    "give me": "gimme",
    "let me": "lemme",
    "come on": "c'mon",
    "do not": "don't",
    "did not": "didn't",
    "would not": "wouldn't",
    "could not": "couldn't",
    "should not": "shouldn't",
    "will not": "won't",
    "cannot": "can't",
    "i am": "i'm",
    "i have": "i've",
    "i would": "i'd",
    "they are": "they're",
    "we are": "we're",
    "you are": "you're",
    "it is": "it's",
    "that is": "that's",
    "what is": "what's",
    "he is": "he's",
    "she is": "she's",
}

A1_WORDS: frozenset[str] = frozenset(
    {
        "i",
        "you",
        "he",
        "she",
        "it",
        "we",
        "they",
        "me",
        "him",
        "her",
        "us",
        "them",
        "a",
        "an",
        "the",
        "and",
        "but",
        "or",
        "so",
        "if",
        "of",
        "in",
        "on",
        "at",
        "to",
        "for",
        "with",
        "by",
        "from",
        "up",
        "as",
        "is",
        "was",
        "are",
        "were",
        "be",
        "been",
        "being",
        "have",
        "has",
        "had",
        "do",
        "does",
        "did",
        "will",
        "would",
        "could",
        "should",
        "may",
        "might",
        "can",
        "shall",
        "must",
        "that",
        "this",
        "these",
        "those",
        "what",
        "which",
        "who",
        "when",
        "where",
        "why",
        "how",
        "all",
        "some",
        "any",
        "no",
        "not",
        "more",
        "very",
        "just",
        "get",
        "go",
        "come",
        "make",
        "know",
        "think",
        "see",
        "look",
        "want",
        "give",
        "say",
        "tell",
        "ask",
        "work",
        "use",
        "take",
        "put",
        "find",
        "let",
        "good",
        "new",
        "first",
        "last",
        "long",
        "great",
        "little",
        "own",
        "right",
        "big",
        "high",
        "small",
        "large",
        "old",
        "same",
        "next",
        "few",
        "both",
        "here",
        "there",
        "now",
        "then",
        "only",
        "also",
        "back",
        "still",
        "well",
        "even",
        "need",
        "feel",
        "try",
        "call",
        "keep",
        "turn",
        "move",
        "live",
        "play",
        "run",
        "help",
        "start",
        "show",
        "hear",
        "stop",
        "read",
        "always",
        "never",
        "every",
        "much",
        "too",
        "than",
        "about",
        "out",
        "about",
        "over",
        "after",
        "before",
        "again",
        "because",
        "like",
        "really",
        "time",
        "year",
        "people",
        "way",
        "day",
        "man",
        "woman",
        "child",
        "world",
        "life",
        "hand",
        "part",
        "place",
        "thing",
        "case",
        "week",
        "company",
        "system",
        "program",
        "question",
        "money",
        "home",
        "number",
        "night",
        "point",
        "today",
        "water",
        "room",
        "mother",
        "area",
        "story",
        "fact",
        "month",
        "lot",
        "right",
        "study",
        "book",
        "eye",
        "job",
        "word",
        "business",
        "issue",
        "side",
        "kind",
        "head",
        "house",
        "service",
        "friend",
        "father",
        "power",
        "hour",
        "game",
        "line",
        "end",
        "among",
        "never",
        "last",
        "found",
        "still",
        "since",
        "must",
        "came",
        "had",
        "said",
        "has",
    }
)
